[package]
name = "factor"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
name = "factor"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[profile.bench]
opt-level = 2

[[bin]]
name = "factor"
path = "src/bin/main.rs"

[[bench]]
name = "ecm_param"
harness = false

[[bench]]
name = "compare_all"
harness = false

[[bench]]
name = "perfect_power"
harness = false

[[bench]]
name = "multipoint_evaluation"
harness = false
